#  Your global data folder is controlled by the dir.data configuration option.
#  All *.json and module.exports values from *.js files in this directory will
#  be added into a global data object available to all templates.

#  TIP: Variables from this file can be accessed from template files with: {{ site.variable }}. For example: {{ site.title }} or {{ site.description }}

title: "Projeto Acalanto DF" # Appears after the title Page eg. Title - Web Starter
slogan: "Sua ajuda pode salvar vidas"
description: "Adotar é o bicho!"
meta_data:
 twitter: "@"
 default_social_image: "/static/default_social_image.jpg"

texts:
  presentation: "Somos um grupo de protetores independentes que cuidam, zelam e promovem a adoção de centenas de animais! 🐱 🧡🐶"
  highlight: "Vídeos sobre o projeto"
  message: "Conheça mais sobre nós"
  products: "Nossos amigos!"
  sobrenos: "Enquanto as pessoas que abandonam animais nas ruas à própria sorte, não se educarem no sentindo DO NÃO ABANDONO, E SIM DA CASTRAÇÃO, cenas como essas são rotina em nossa batalha árdua, cansativa, desgastante. Acolher um animal de rua, resgatar, essa parte é a mais fácil. Difícil pra mim como protetora: Dinheiro para ração de qualidade. Dinheiro para vacinas. Dinheiro para as castrações. Eu falo por mim, vivo fazendo rifa atras de rifa, bazar, peço madrinhas e padrinhos de castração, pois somente assim com muita luta e a ajuda de várias pessoas consigo fazer o meu trabalho voluntário voltado aos amigos de 4 patas. Proteção animal é uma linha tênue para não adoecer emocionalmente, fisicamente e financeiramente. O desgaste físico por estar sempre na correria e na adrenalina de conseguir salvar mais uma vidinha, vitima da covardia de outra pessoa, que deveria dar o devido respeito e não o fez. O desgaste emocional, devido a tanta crueldade e maldade, me mata por dentro. O desgaste financeiro, dividas atrás de dividas. Meu trabalho voluntário como Protetora de Animais é isso. O faço por amor e compaixão à eles, pois se colocarmos na ponta do lápis os prós e os contras, dificilmente prosseguiríamos. Espero um dia conseguir conscientizar mais e mais pessoas a respeito do amor aos nossos amigos de 4 patas!"
  

# Careful! Use quotes around your links.
navigation:
  - name: Sobre nós
    url: '#highlight'
    description: Learn about the tools we used
  - name: Conheça nossos amigos
    url: '#product-list'
    description: Ajude nossos animais


currency_symbol: R$

social_networks:
  blog:
    url: "https://linktr.ee/projetoacalantodf"
    icon: "fas fa-blog"
  email:
    url: "projetoacalantodf@gmail.com"
    icon: "fas fa-envelope-square"
    protocol: "mailto"
  facebook:
    url: "https://www.facebook.com/projetoacalantodf"
    icon: "fab fa-facebook-square"
  instagram:
    url: "https://www.instagram.com/projetoacalantodf/"
    icon: "fab fa-instagram"
  youtube:
    url: "https://www.youtube.com/channel/UCPkQVP3gP_sYR8qhaCOD-PA"
    icon: "fab fa-youtube"


url: "https://www.instagram.com/projetoacalantodf"
author: "Projeto Acalanto DF"

