#  Your global data folder is controlled by the dir.data configuration option.
#  All *.json and module.exports values from *.js files in this directory will
#  be added into a global data object available to all templates.

#  TIP: Variables from this file can be accessed from template files with: {{ site.variable }}. For example: {{ site.title }} or {{ site.description }}

title: "JAM Stack e-commerce template" # Appears after the title Page eg. Title - Web Starter
slogan: "using a set of powerfull tools"
description: "An e-commerce website built with 11ty.js, TailwindCSS and Foxy.io"
meta_data:
 twitter: "@"
 default_social_image: "/static/default_social_image.jpg"

texts:
  presentation: "Go on! Tweak this site to meet your needs! You'll discover you'll have the perfect site in no time."
  highlight: "Here are some of our highlights"
  message: "Here is a message for you."
  products: "Our amazing products!"
  

# Careful! Use quotes around your links.
navigation:
  - name: Presentation
    url: '#presentation'
    description: This is our awesome store
  - name: Tools used
    url: '#highlight'
    description: Learn about the tools we used
  - name: Our products
    url: '#product-list'
    description: Check out the cool products we have


currency_symbol: $

social_networks:
  blog:
    url: "https://www.foxy.io/blog/"
    icon: "fas fa-blog-square"
  email:
    url: "hello@foxy.io"
    icon: "fas fa-envelope-square"
    protocol: "mailto"
  facebook:
    url: "https://www.facebook.com/foxycart"
    icon: "fab fa-facebook-square"
  twitter:
    url: "https://twitter.com/foxycart"
    icon: "fab fa-twitter-square"
  youtube:
    url: "https://www.youtube.com/foxycart"
    icon: "fab fa-youtube"


url: "https://foxy.io/"
author: "Foxy.io"

