#  Your global data folder is controlled by the dir.data configuration option.
#  All *.json and module.exports values from *.js files in this directory will
#  be added into a global data object available to all templates.

#  TIP: Variables from this file can be accessed from template files with: {{ site.variable }}. For example: {{ site.title }} or {{ site.description }}

title: "Projeto Acalanto DF" # Appears after the title Page eg. Title - Web Starter
slogan: "Sua ajuda pode salvar vidas"
description: "Adotar é o bicho!"
meta_data:
 twitter: "@"
 default_social_image: "/static/default_social_image.jpg"

texts:
  presentation: "Somos um grupo de protetores independentes que cuidam, zelam e promovem a adoção de centenas de animais! 🐱 🧡🐶"
  highlight: "Vídeos sobre o projeto"
  message: "Conheça mais sobre nós"
  products: "Nossos amigos!"
  

# Careful! Use quotes around your links.
navigation:
  - name: Sobre nós
    url: '#highlight'
    description: Learn about the tools we used
  - name: Conheça nossos amigos
    url: '#product-list'
    description: Ajude nossos animais


currency_symbol: $

social_networks:
  blog:
    url: "https://linktr.ee/projetoacalantodf"
    icon: "fas fa-blog-square"
  email:
    url: "projetoacalantodf@gmail.com"
    icon: "fas fa-envelope-square"
    protocol: "mailto"
  facebook:
    url: "https://www.facebook.com/projetoacalantodf"
    icon: "fab fa-facebook-square"
  instagram:
    url: "https://www.instagram.com/projetoacalantodf/"
    icon: "fab  fa-instagram-square"
  youtube:
    url: "https://www.youtube.com/channel/UCPkQVP3gP_sYR8qhaCOD-PA"
    icon: "fab fa-youtube"


url: "https://www.instagram.com/projetoacalantodf"
author: "Projeto Acalanto DF"

